### ISSUE TITLE
Cancellations now allowed before 24hr.

### ISSUE THREAD

**Issue by juandefelix** [juandefelix/rails_makeup_scheduler#27]
Check the form in cancellations/new. Users can't notify absences before 24 hr.

**Comment by cdelmoral** [comment]
I think the problem here is related with time zones. When sending the form we create a `DateTime` with the selected date and time, but the time zone is set to the server's one.

Also, test `"when submiting a date that is too early"` passes since the set time is in the past, that should be corrected.

**Comment by juandefelix** [comment]
:+1: I'll check it ASAP.

**Comment by juandefelix** [comment]
Running `heroku config:add TZ="America/Chicago"` in the terminal or setting the TZ global variable in the Heroku console solves the problem. 
Already took care of it.
